name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NEXT_PUBLIC_API_KEY_TICKET_LISTS: ${{ secrets.NEXT_PUBLIC_API_KEY_TICKET_LISTS }}
  NEXT_PUBLIC_AUTH_DOMAIN_TICKET_LISTS: ${{ secrets.NEXT_PUBLIC_AUTH_DOMAIN_TICKET_LISTS }}
  NEXT_PUBLIC_DATABASE_URL_TICKET_LISTS: ${{ secrets.NEXT_PUBLIC_DATABASE_URL_TICKET_LISTS }}
  NEXT_PUBLIC_PROJECT_ID_TICKET_LISTS: ${{ secrets.NEXT_PUBLIC_PROJECT_ID_TICKET_LISTS }}
  NEXT_PUBLIC_STORAGE_BUCKET_TICKET_LISTS: ${{ secrets.NEXT_PUBLIC_STORAGE_BUCKET_TICKET_LISTS }}
  NEXT_PUBLIC_MESSAGING_SENDER_ID_TICKET_LISTS: ${{ secrets.NEXT_PUBLIC_MESSAGING_SENDER_ID_TICKET_LISTS }}
  NEXT_PUBLIC_APP_ID_TICKET_LISTS: ${{ secrets.NEXT_PUBLIC_APP_ID_TICKET_LISTS }}
  
  NEXT_PUBLIC_API_KEY_LINE_CHART: ${{ secrets.NEXT_PUBLIC_API_KEY_LINE_CHART }}
  NEXT_PUBLIC_AUTH_DOMAIN_LINE_CHART: ${{ secrets.NEXT_PUBLIC_AUTH_DOMAIN_LINE_CHART }}
  NEXT_PUBLIC_DATABASE_URL_LINE_CHART: ${{ secrets.NEXT_PUBLIC_DATABASE_URL_LINE_CHART }}
  NEXT_PUBLIC_PROJECT_ID_LINE_CHART: ${{ secrets.NEXT_PUBLIC_PROJECT_ID_LINE_CHART }}
  NEXT_PUBLIC_STORAGE_BUCKET_LINE_CHART: ${{ secrets.NEXT_PUBLIC_STORAGE_BUCKET_LINE_CHART }}
  NEXT_PUBLIC_MESSAGING_SENDER_ID_LINE_CHART: ${{ secrets.NEXT_PUBLIC_MESSAGING_SENDER_ID_LINE_CHART }}
  NEXT_PUBLIC_APP_ID_LINE_CHART: ${{ secrets.NEXT_PUBLIC_APP_ID_LINE_CHART }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_NAME }}  # Menggunakan secret APP_NAME
          slot-name: "Production"
          publish-profile: ${{ secrets.APP_PUBLISH_PROFILE }}  # Menggunakan secret APP_PUBLISH_PROFILE
          package: ./build/standalone
